[package]
name = "aoc16-05"
version = "0.1.0"
authors = ["Fabian Würfl <fabian.wuerfl@gmx.at>"]
edition = "2018"

[dependencies]
aoc_utils = { path = "../../../../aoc-utils/" }
lazy_static = "1.4"
regex = "1.3"
md-5 = "0.8.0"
sha-1 = "0.8.1"