[package]
name = "aoc18-04"
version = "0.1.0"
authors = ["Fabian Würfl <bafdyce@tuta.io>"]

[dependencies]
aoc_utils = { path = "../../../../aoc-utils/" }
lazy_static = "1.2.0"
regex = "1.0.6"
md-5 = "0.8.0"
sha-1 = "0.8.1"
