[package]
name = "aoc-2019-01"
version = "0.1.0"
authors = ["Fabian Würfl <bafdyce@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_import_magic = { path = "../aoc_import_magic" }
