[package]
name = "aoc-2019-01"
version = "0.1.0"
authors = ["Fabian Würfl <bafdyce@tuta.io>"]
edition = "2018"

[features]
unstable = []

[dependencies]
aoc_import_magic = { path = "../aoc_import_magic" }
